version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN"
      - run:
          name: Revoke npm token
          command: npm token revoke -all
	  - run:
	      name: Create a new token
		  command: npm token create

  
workflows:
  build_test:
    jobs:
      - run_tests
