version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run: echo "DemoBuild"
      - run: echo "Install Jfrog CLI"
      - run: curl -fL https://getcli.jfrog.io | sh
      - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive=false
      - run: touch "build-artifacts"
      - run: ./jfrog rt c show
      - run: ./jfrog rt u "build-artifacts" "Demo-npm-local" --build-name=JCircleCI-Demo --build-number=$CIRCLE_BUILD_NUM --flat=true
