Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@saisankar10 
Learn Git and GitHub without any code!
Using the Hello World guide, you’ll start a branch, write comments, and open a pull request.


saisankar10
/
Npm-CircleCI-Jfrog
0
0
0
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Npm-CircleCI-Jfrog/.circleci/config.yml
@saisankar10
saisankar10 Update config.yml
Latest commit 46be835 5 days ago
 History
 1 contributor
37 lines (35 sloc)  958 Bytes
  
version: 2.1
jobs:
  run_tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - persist_to_workspace:
          root: ~/repo
          paths: .
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  
workflows:
  build_test:
    jobs:
      - run_tests
      
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
