version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "DemoBuild"
      - run: echo "Install Jfrog CLI"
      - run: curl -fL https://getcli.jfrog.io | sh
      - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive=false
      - run: touch "build-artifacts"
      - run: ./jfrog rt c show
      - run: ./jfrog rt npmc
      - run: ./jfrog rt npmi npm-virtual-demo --build-name=bootstrap --build-number=1.0.0
      - run: ./jfrog rt bag bootstrap 1.0.0
      - run: ./jfrog rt bce bootstrap 1.0.0
      - run: ./jfrog rt npmp npm-virtual-demo --build-name=bootstrap --build-number=1.0.0
      - run: ./jfrog rt bp bootstrap 1.0.0
      - run: ./jfrog rt bpr bootstrap 1.0.0 npm-virtual-demo
