version: 2
# Build Artifacts and Publish to Jfrog
jobs:
  upload-artifact:
    docker:
      - image: circleci/openjdk:8u232-jdk-stretch-browsers
    steps:
      - checkout
      # Install JFrog CLI
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive=false
            ./jfrog rt c show
            ./jfrog rt u Demo-npm-local --build-name=Demo-Build --build-number=$CIRCLE_BUILD_NUM
            touch build-artifacts
            ./jfrog rt bce Demo-Build $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp Demo-Build $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory
