version: 2.1
jobs:
  Slack_setup:
    machine:
        image: 'ubuntu-1604:201903-01'
    steps:
       - slack/approval:
          message: "Time to Change the Authentication Token, Please access the URL and Approve to proceed to revoke the existing Token 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'" # Optional: Enter your own message
          mentions: "W015C9HCQSH,W01232MH4GM,W016RHZPZ1A" # Optional: Enter the Slack IDs of any user or group (sub_team) to be mentioned
          color: "#42e2f4" # Optional: Assign custom colors for each approval message
          webhook: "$SLACK_WEBHOOK" # Optional: Enter a specific webhook here or the default will use $SLACK_WEBHOOK
          url: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
  Revoke_Auth_token:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - persist_to_workspace:
          root: ~/repo
          paths: .
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Revoke npm token
          command: npm token revoke $npm_id
orbs:
  slack: circleci/slack@3.4.2
  
workflows:
    Build:
      jobs:
        - Slack_setup
        - hold:
            type: approval
            requires:
              - Slack_setup
        - Revoke_Auth_token:
            requires:
              - hold
        
